// ============================================================
//  BRANDS SEED DATA — Real protein.tn brands
//  54 official supplement & nutrition brands
// ============================================================

const STORAGE_BASE = '/uploads';

export const brandsSeedData = [
  {
    designation_fr: 'OLIMP SPORT NUTRITION',
    designation: 'OLIMP SPORT NUTRITION',
    slug: 'olimp-sport-nutrition',
    active: true,
    featured: true,
    order: 1,
    logo: { url: `${STORAGE_BASE}/brands/September2023/HGnPbXKfsY0t2gYFARg4.webp`, alt: 'Olimp Sport Nutrition Logo' },
  },
  {
    designation_fr: 'DYMATIZE',
    designation: 'DYMATIZE',
    slug: 'dymatize',
    active: true,
    featured: true,
    order: 2,
    logo: { url: `${STORAGE_BASE}/brands/July2023/fZHXBWTbLhv8EJhvjrJj.webp`, alt: 'Dymatize Logo' },
  },
  {
    designation_fr: 'NUTREX RESEARCH',
    designation: 'NUTREX RESEARCH',
    slug: 'nutrex-research',
    active: true,
    featured: true,
    order: 3,
    logo: { url: `${STORAGE_BASE}/brands/July2023/GKTUrYH9bZsH3ghZyF3U.webp`, alt: 'Nutrex Research Logo' },
  },
  {
    designation_fr: 'API',
    designation: 'API',
    slug: 'api',
    active: true,
    featured: true,
    order: 4,
    logo: { url: `${STORAGE_BASE}/brands/August2023/XgMsjqTRZMs5U5Tbed9c.webp`, alt: 'API Logo' },
  },
  {
    designation_fr: 'BIOTECH USA',
    designation: 'BIOTECH USA',
    slug: 'biotech-usa',
    active: true,
    featured: true,
    order: 5,
    logo: { url: `${STORAGE_BASE}/brands/August2023/PKxthbj11BDXT3X6Rsdl.webp`, alt: 'Biotech USA Logo' },
  },
  {
    designation_fr: 'RULE 1',
    designation: 'RULE 1',
    slug: 'rule-1',
    active: true,
    featured: true,
    order: 6,
    logo: { url: `${STORAGE_BASE}/brands/September2023/eXtjsCmjaruhIfglgaMI.webp`, alt: 'Rule 1 Logo' },
  },
  {
    designation_fr: 'BPI SPORTS',
    designation: 'BPI SPORTS',
    slug: 'bpi-sports',
    active: true,
    featured: true,
    order: 7,
    logo: { url: `${STORAGE_BASE}/brands/September2023/lxSQgMmRXt1qG8DHVjKb.webp`, alt: 'BPI Sports Logo' },
  },
  {
    designation_fr: 'BSN SUPPLEMENTS',
    designation: 'BSN SUPPLEMENTS',
    slug: 'bsn-supplements',
    active: true,
    featured: true,
    order: 8,
    logo: { url: `${STORAGE_BASE}/brands/September2023/QZQQkJpiF0XHgDEDZ0TK.webp`, alt: 'BSN Supplements Logo' },
  },
  {
    designation_fr: 'CELLUCOR',
    designation: 'CELLUCOR',
    slug: 'cellucor',
    active: true,
    featured: true,
    order: 9,
    logo: { url: `${STORAGE_BASE}/brands/August2023/J0HJ1u078CzvBxvucTJe.webp`, alt: 'Cellucor Logo' },
  },
  {
    designation_fr: 'CHALLENGER NUTRITION',
    designation: 'CHALLENGER NUTRITION',
    slug: 'challenger-nutrition',
    active: true,
    featured: true,
    order: 10,
    logo: { url: `${STORAGE_BASE}/brands/September2023/cZcCZb5n0uaVEukUm2kV.webp`, alt: 'Challenger Nutrition Logo' },
  },
  {
    designation_fr: 'KEVIN LEVRONE',
    designation: 'KEVIN LEVRONE',
    slug: 'kevin-levrone',
    active: true,
    featured: true,
    order: 11,
    logo: { url: `${STORAGE_BASE}/brands/August2023/bW4BxD3hbNnXhHSoz4KK.webp`, alt: 'Kevin Levrone Logo' },
  },
  {
    designation_fr: 'MUSCLETECH',
    designation: 'MUSCLETECH',
    slug: 'muscletech',
    active: true,
    featured: true,
    order: 12,
    logo: { url: `${STORAGE_BASE}/brands/August2023/myX1bQ4RLJaBusRsIzfg.webp`, alt: 'Muscletech Logo' },
  },
  {
    designation_fr: 'MUTANT',
    designation: 'MUTANT',
    slug: 'mutant',
    active: true,
    featured: true,
    order: 13,
    logo: { url: `${STORAGE_BASE}/brands/August2023/Blbx6aPbRpqrDe57lYy2.webp`, alt: 'Mutant Logo' },
  },
  {
    designation_fr: 'Optimum Nutrition',
    designation: 'Optimum Nutrition',
    slug: 'optimum-nutrition',
    active: true,
    featured: true,
    order: 14,
    logo: { url: `${STORAGE_BASE}/brands/August2023/7tLlXyUOodHBfDC1SY5K.webp`, alt: 'Optimum Nutrition Logo' },
  },
  {
    designation_fr: 'OstroVit',
    designation: 'OstroVit',
    slug: 'ostrovit',
    active: true,
    featured: false,
    order: 15,
    logo: { url: `${STORAGE_BASE}/brands/August2023/FukiSD5RdviqLsymBw5v.webp`, alt: 'OstroVit Logo' },
  },
  {
    designation_fr: 'Quamtrax',
    designation: 'Quamtrax',
    slug: 'quamtrax',
    active: true,
    featured: false,
    order: 16,
    logo: { url: `${STORAGE_BASE}/brands/August2023/Zw6C4QE5CJ3jhKNt20gS.webp`, alt: 'Quamtrax Logo' },
  },
  {
    designation_fr: 'Real Pharm',
    designation: 'Real Pharm',
    slug: 'real-pharm',
    active: true,
    featured: false,
    order: 17,
    logo: { url: `${STORAGE_BASE}/brands/August2023/B5cQJKyjj58klNscRK2z.webp`, alt: 'Real Pharm Logo' },
  },
  {
    designation_fr: 'Redcon1',
    designation: 'Redcon1',
    slug: 'redcon1',
    active: true,
    featured: false,
    order: 18,
    logo: { url: `${STORAGE_BASE}/brands/August2023/5ifBv4h2RNXSjoBs1jnB.webp`, alt: 'Redcon1 Logo' },
  },
  {
    designation_fr: 'SCITEC NUTRITION',
    designation: 'SCITEC NUTRITION',
    slug: 'scitec-nutrition',
    active: true,
    featured: true,
    order: 19,
    logo: { url: `${STORAGE_BASE}/brands/August2023/j1WOOW7rHjDm9lhyAL2E.webp`, alt: 'Scitec Nutrition Logo' },
  },
  {
    designation_fr: 'Ultimate Nutrition',
    designation: 'Ultimate Nutrition',
    slug: 'ultimate-nutrition',
    active: true,
    featured: false,
    order: 20,
    logo: { url: `${STORAGE_BASE}/brands/September2023/dbWyAQkKmvQIhHEKtAOK.webp`, alt: 'Ultimate Nutrition Logo' },
  },
  {
    designation_fr: 'Universal Nutrition',
    designation: 'Universal Nutrition',
    slug: 'universal-nutrition',
    active: true,
    featured: false,
    order: 21,
    logo: { url: `${STORAGE_BASE}/brands/August2023/ddolbPbSKII5II2lySeP.webp`, alt: 'Universal Nutrition Logo' },
  },
  {
    designation_fr: 'MusclePharm',
    designation: 'MusclePharm',
    slug: 'musclepharm',
    active: true,
    featured: false,
    order: 22,
    logo: { url: `${STORAGE_BASE}/brands/August2023/sP3N7TnCbIPh1IVX5aER.webp`, alt: 'MusclePharm Logo' },
  },
  {
    designation_fr: 'Invictus',
    designation: 'Invictus',
    slug: 'invictus',
    active: true,
    featured: false,
    order: 23,
    logo: { url: `${STORAGE_BASE}/brands/August2023/ag7dXWxdplc6gesMHc7o.webp`, alt: 'Invictus Logo' },
  },
  {
    designation_fr: 'MYPROTEIN',
    designation: 'MYPROTEIN',
    slug: 'myprotein',
    active: true,
    featured: true,
    order: 24,
    logo: { url: `${STORAGE_BASE}/brands/August2023/V2oxUHMU7sLDvVPR6jz7.webp`, alt: 'Myprotein Logo' },
  },
  {
    designation_fr: 'PROACTIVE',
    designation: 'PROACTIVE',
    slug: 'proactive',
    active: true,
    featured: false,
    order: 25,
    logo: { url: `${STORAGE_BASE}/brands/August2023/H4Kw4cIoGgjWjACkJNcR.webp`, alt: 'ProActive Logo' },
  },
  {
    designation_fr: 'GALVANIZE CHROME',
    designation: 'GALVANIZE CHROME',
    slug: 'galvanize-chrome',
    active: true,
    featured: false,
    order: 26,
    logo: { url: `${STORAGE_BASE}/brands/September2023/ZRIH2Olxt7i0vog5F1lr.JPG`, alt: 'Galvanize Chrome Logo' },
  },
  {
    designation_fr: 'SOTEK NUTRITION',
    designation: 'SOTEK NUTRITION',
    slug: 'sotek-nutrition',
    active: true,
    featured: false,
    order: 27,
    logo: { url: `${STORAGE_BASE}/brands/August2023/slMfHTocF5ZB5S8U2TFS.webp`, alt: 'Sotek Nutrition Logo' },
  },
  {
    designation_fr: 'ACTIVLAB',
    designation: 'ACTIVLAB',
    slug: 'activlab',
    active: true,
    featured: false,
    order: 28,
    logo: { url: `${STORAGE_BASE}/brands/August2023/UCkxKYxgL5yJ1CDJqWHp.webp`, alt: 'Activlab Logo' },
  },
  {
    designation_fr: 'HX NUTRITION',
    designation: 'HX NUTRITION',
    slug: 'hx-nutrition',
    active: true,
    featured: false,
    order: 29,
    logo: { url: `${STORAGE_BASE}/brands/August2023/kKoiY6uugsWb0nVqzAvx.webp`, alt: 'HX Nutrition Logo' },
  },
  {
    designation_fr: 'PRO CELL',
    designation: 'PRO CELL',
    slug: 'pro-cell',
    active: true,
    featured: false,
    order: 30,
    logo: { url: `${STORAGE_BASE}/brands/September2023/q0T41TfjVFBWYXbSX6zN.webp`, alt: 'Pro Cell Logo' },
  },
  {
    designation_fr: 'SCIVATION',
    designation: 'SCIVATION',
    slug: 'scivation',
    active: true,
    featured: false,
    order: 31,
    logo: { url: `${STORAGE_BASE}/brands/September2023/cLClwIVVZvNHoCprsxBp.webp`, alt: 'Scivation Logo' },
  },
  {
    designation_fr: 'MR.X V-Shape Supps',
    designation: 'MR.X V-Shape Supps',
    slug: 'mr-x-v-shape-supps',
    active: true,
    featured: false,
    order: 32,
    logo: { url: `${STORAGE_BASE}/brands/September2023/s2X9QGOG7IddpPFNubEQ.webp`, alt: 'Mr. X V-Shape Supps Logo' },
  },
  {
    designation_fr: 'SCENIT NUTRITION',
    designation: 'SCENIT NUTRITION',
    slug: 'scenit-nutrition',
    active: true,
    featured: false,
    order: 33,
    logo: { url: `${STORAGE_BASE}/brands/September2023/2mdSIgnvlKMash6LhDLw.webp`, alt: 'Scenit Nutrition Logo' },
  },
  {
    designation_fr: 'KONG SPORT NUTRITION',
    designation: 'KONG SPORT NUTRITION',
    slug: 'kong-sport-nutrition',
    active: true,
    featured: false,
    order: 34,
    logo: { url: `${STORAGE_BASE}/brands/September2023/125YKjML6n4hSMN1yTCH.webp`, alt: 'Kong Sport Nutrition Logo' },
  },
  {
    designation_fr: "GOLD\u2019S GYM",
    designation: "GOLD\u2019S GYM",
    slug: 'golds-gym',
    active: true,
    featured: false,
    order: 35,
    logo: { url: `${STORAGE_BASE}/brands/September2023/kd0MkkfbLEasp80CpWK6.webp`, alt: "Gold's Gym Logo" },
  },
  {
    designation_fr: 'ERIC FAVRE',
    designation: 'ERIC FAVRE',
    slug: 'eric-favre',
    active: true,
    featured: false,
    order: 36,
    logo: { url: `${STORAGE_BASE}/brands/September2023/s8IEz1D6OEeCdSHxqGSP.webp`, alt: 'Eric Favre Logo' },
  },
  {
    designation_fr: 'JNX SPORTS',
    designation: 'JNX SPORTS',
    slug: 'jnx-sports',
    active: true,
    featured: false,
    order: 37,
    logo: { url: `${STORAGE_BASE}/brands/September2023/6d90fcgejQHTUnGPmHIs.webp`, alt: 'JNX Sports Logo' },
  },
  {
    designation_fr: 'NUTRAGENICS',
    designation: 'NUTRAGENICS',
    slug: 'nutragenics',
    active: true,
    featured: false,
    order: 38,
    logo: { url: `${STORAGE_BASE}/brands/September2023/LdfhYFnoLnrATrFifnUU.webp`, alt: 'NutraGenics Logo' },
  },
  {
    designation_fr: 'FA ENGINEERED NUTRITION',
    designation: 'FA ENGINEERED NUTRITION',
    slug: 'fa-engineered-nutrition',
    active: true,
    featured: false,
    order: 39,
    logo: { url: `${STORAGE_BASE}/brands/September2023/yhnzDdDsAOJgp1FMSLDb.webp`, alt: 'FA Engineered Nutrition Logo' },
  },
  {
    designation_fr: 'MONSTER',
    designation: 'MONSTER',
    slug: 'monster',
    active: true,
    featured: false,
    order: 40,
    logo: { url: `${STORAGE_BASE}/brands/September2023/ZscuOiAReNr2s1zl77mq.webp`, alt: 'Monster Logo' },
  },
  {
    designation_fr: 'APPLIED NUTRITION',
    designation: 'APPLIED NUTRITION',
    slug: 'applied-nutrition',
    active: true,
    featured: true,
    order: 41,
    logo: { url: `${STORAGE_BASE}/brands/September2023/1e11CLR7ecqYokmirMFU.webp`, alt: 'Applied Nutrition Logo' },
  },
  {
    designation_fr: 'TREC NUTRITION',
    designation: 'TREC NUTRITION',
    slug: 'trec-nutrition',
    active: true,
    featured: false,
    order: 42,
    logo: { url: `${STORAGE_BASE}/brands/September2023/oUfJwWvSeDV6PFhzsYUm.webp`, alt: 'Trec Nutrition Logo' },
  },
  {
    designation_fr: '7NUTRITION',
    designation: '7NUTRITION',
    slug: '7nutrition',
    active: true,
    featured: false,
    order: 43,
    logo: { url: `${STORAGE_BASE}/brands/September2023/7VDCK7YLf1upqvyQwAFL.webp`, alt: '7Nutrition Logo' },
  },
  {
    designation_fr: 'SOUL PROJECT',
    designation: 'SOUL PROJECT',
    slug: 'soul-project',
    active: true,
    featured: false,
    order: 44,
    logo: { url: `${STORAGE_BASE}/brands/September2023/ry6bqE02AJbZ8xE0DKkK.webp`, alt: 'Soul Project Logo' },
  },
  {
    designation_fr: 'IHS TECHNOLOGY SUPPLEMENTS',
    designation: 'IHS TECHNOLOGY SUPPLEMENTS',
    slug: 'ihs-technology-supplements',
    active: true,
    featured: false,
    order: 45,
    logo: { url: `${STORAGE_BASE}/brands/January2024/LOtP0VFXdlstdD3H2GSI.webp`, alt: 'IHS Technology Supplements Logo' },
  },
  {
    designation_fr: 'MND FITNESS',
    designation: 'MND FITNESS',
    slug: 'mnd-fitness',
    active: true,
    featured: false,
    order: 46,
    logo: { url: `${STORAGE_BASE}/brands/January2024/jVc5GiKIiD9GStepIscH.webp`, alt: 'MND Fitness Logo' },
  },
  {
    designation_fr: 'JX FITNESS',
    designation: 'JX FITNESS',
    slug: 'jx-fitness',
    active: true,
    featured: false,
    order: 47,
    logo: { url: `${STORAGE_BASE}/brands/January2024/ChWTywlKrusqBx66nsdy.webp`, alt: 'JX Fitness Logo' },
  },
  {
    designation_fr: 'GSN Great Sport Nutrition',
    designation: 'GSN Great Sport Nutrition',
    slug: 'gsn-great-sport-nutrition',
    active: true,
    featured: false,
    order: 48,
    logo: { url: `${STORAGE_BASE}/brands/August2024/uyJnHqlpRz3szPUtNOyP.webp`, alt: 'GSN Great Sport Nutrition Logo' },
  },
  {
    designation_fr: 'BIG RAMY LABS',
    designation: 'BIG RAMY LABS',
    slug: 'big-ramy-labs',
    active: true,
    featured: false,
    order: 49,
    logo: { url: `${STORAGE_BASE}/brands/September2024/S5gcbEoftyQcSqDC5htA.webp`, alt: 'Big Ramy Labs Logo' },
  },
  {
    designation_fr: 'VICTOR MARTINEZ',
    designation: 'VICTOR MARTINEZ',
    slug: 'victor-martinez',
    active: true,
    featured: false,
    order: 50,
    logo: { url: `${STORAGE_BASE}/brands/February2025/immH5NEJj0RiAC9tfl4z.webp`, alt: 'Victor Martinez Logo' },
  },
  {
    designation_fr: 'WARRIOR SUPPLEMENTS',
    designation: 'WARRIOR SUPPLEMENTS',
    slug: 'warrior-supplements',
    active: true,
    featured: false,
    order: 51,
    logo: { url: `${STORAGE_BASE}/brands/April2025/2Z8FkRBDFRbn7QDlwhQ6.webp`, alt: 'Warrior Supplements Logo' },
  },
  {
    designation_fr: 'USN Ultimate Sports Nutrition',
    designation: 'USN Ultimate Sports Nutrition',
    slug: 'usn-ultimate-sports-nutrition',
    active: true,
    featured: false,
    order: 52,
    logo: { url: `${STORAGE_BASE}/brands/May2025/GZBphc4XrVVq1f3Varm9.webp`, alt: 'USN Ultimate Sports Nutrition Logo' },
  },
  {
    designation_fr: 'YAVA LABS',
    designation: 'YAVA LABS',
    slug: 'yava-labs',
    active: true,
    featured: false,
    order: 53,
    logo: { url: `${STORAGE_BASE}/brands/September2025/uKdjIzlNliMpxPXIyq1n.webp`, alt: 'Yava Labs Logo' },
  },
  {
    designation_fr: 'WILLIAM BONAC',
    designation: 'WILLIAM BONAC',
    slug: 'william-bonac',
    active: true,
    featured: false,
    order: 54,
    logo: { url: `${STORAGE_BASE}/brands/February2026/FKP7ch9ZHlZA5pzTfXJ4.webp`, alt: 'William Bonac Logo' },
  },
];
