export const brandsSeedData = [
  {
    designation_fr: 'Sobitas Pro',
    designation: 'Sobitas Pro',
    slug: 'sobitas-pro',
    description: 'Suppléments de qualité premium pour athlètes sérieux',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: true,
    order: 1,
  },
  {
    designation_fr: 'Sobitas Elite',
    designation: 'Sobitas Elite',
    slug: 'sobitas-elite',
    description: 'Nutrition de performance niveau élite',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: true,
    order: 2,
  },
  {
    designation_fr: 'Sobitas Natural',
    designation: 'Sobitas Natural',
    slug: 'sobitas-natural',
    description: 'Suppléments naturels et végétaux',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: true,
    order: 3,
  },
  {
    designation_fr: 'Sobitas Energy',
    designation: 'Sobitas Energy',
    slug: 'sobitas-energy',
    description: 'Formules énergétiques et pre-workout',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: true,
    order: 4,
  },
  {
    designation_fr: 'Sobitas Mass',
    designation: 'Sobitas Mass',
    slug: 'sobitas-mass',
    description: 'Suppléments de prise de masse et bulk',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: false,
    order: 5,
  },
  {
    designation_fr: 'Sobitas Lean',
    designation: 'Sobitas Lean',
    slug: 'sobitas-lean',
    description: 'Suppléments brûleurs de graisse et sèche',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: false,
    order: 6,
  },
  {
    designation_fr: 'Sobitas Health',
    designation: 'Sobitas Health',
    slug: 'sobitas-health',
    description: 'Suppléments santé et bien-être',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: false,
    order: 7,
  },
  {
    designation_fr: 'Sobitas Gear',
    designation: 'Sobitas Gear',
    slug: 'sobitas-gear',
    description: 'Équipement et accessoires de fitness',
    website_url: 'https://sobitas.tn',
    active: true,
    featured: false,
    order: 8,
  },
];
