// ============================================================
//  CATEGORIES & SUBCATEGORIES SEED DATA — Anti-Gravity / Aerial Fitness Theme
// ============================================================

export const categoriesSeedData = [
  {
    designation_fr: 'Hammocks et Tissus Aériens',
    designation: 'Hammocks & Aerial Fabrics',
    slug: 'hammocks-tissus-aeriens',
    description: 'Hamacs de yoga, tissus aériens et accessoires suspendus pour pratiquer les inversions et les postures anti-gravité en toute sécurité.',
    meta_description: 'Hamacs aériens et tissus pour yoga anti-gravité, inversions et décompression vertébrale.',
    active: true,
    order: 1,
    featured: true,
  },
  {
    designation_fr: 'Équipements de Suspension',
    designation: 'Suspension Equipment',
    slug: 'equipements-suspension',
    description: 'Systèmes d\'entraînement en suspension, sangles TRX alternatives et kits complets pour un entraînement fonctionnel et polyvalent défiant la gravité.',
    meta_description: 'Équipements de suspension professionnels pour entraînement fonctionnel et CrossFit aérien.',
    active: true,
    order: 2,
    featured: true,
  },
  {
    designation_fr: 'Vêtements de Fitness',
    designation: 'Fitness Clothing',
    slug: 'vetements-fitness',
    description: 'Tenues de sport ergonomiques pour yoga aérien, Pilates et fitness en suspension. Matières stretch 4 voies pour une liberté de mouvement maximale.',
    meta_description: 'Vêtements de yoga aérien et fitness en suspension confortables et ergonomiques.',
    active: true,
    order: 3,
    featured: true,
  },
  {
    designation_fr: 'Accessoires de Yoga',
    designation: 'Yoga Accessories',
    slug: 'accessoires-yoga',
    description: 'Blocs, sangles, rouleaux de mousse et accessoires pour accompagner votre pratique du yoga aérien et au sol.',
    meta_description: 'Accessoires de yoga aérien, blocs, sangles et rouleaux pour améliorer votre pratique.',
    active: true,
    order: 4,
    featured: false,
  },
  {
    designation_fr: 'Kits d\'Entraînement',
    designation: 'Training Kits',
    slug: 'kits-entrainement',
    description: 'Packs et kits complets pour débutants ou confirmés en fitness aérien. Tout le nécessaire pour commencer ou progresser dans votre pratique anti-gravité.',
    meta_description: 'Kits d\'entraînement complets pour yoga aérien, Pilates et fitness en suspension.',
    active: true,
    order: 5,
    featured: true,
  },
  {
    designation_fr: 'Mats et Tapis',
    designation: 'Mats & Rugs',
    slug: 'mats-tapis',
    description: 'Tapis de yoga et de fitness anti-dérapants avec grip, conçus pour les pratiques au sol combinées aux exercices aériens.',
    meta_description: 'Tapis de yoga anti-dérapants pour fitness aérien et pratiques combinées sol-hamac.',
    active: true,
    order: 6,
    featured: false,
  },
  {
    designation_fr: 'Rigs et Structures',
    designation: 'Rigs & Structures',
    slug: 'rigs-structures',
    description: 'Portiques, rigs et structures d\'ancrage professionnels pour installer vos hamacs et équipements aériens à domicile ou en studio.',
    meta_description: 'Portiques et structures d\'ancrage pour hamacs aériens et équipements de fitness anti-gravité.',
    active: true,
    order: 7,
    featured: false,
  },
  {
    designation_fr: 'Compléments de Bien-Être',
    designation: 'Well-being Supplements',
    slug: 'complements-bien-etre',
    description: 'Huiles essentielles, crèmes musculaires et compléments alimentaires pour favoriser la récupération et le bien-être après une session de fitness aérien.',
    meta_description: 'Compléments de récupération et bien-être pour les pratiquants de fitness aérien.',
    active: true,
    order: 8,
    featured: false,
  },
];

export const subcategoriesSeedData = [
  // === Hammocks et Tissus Aériens ===
  {
    designation: 'Hammocks Simples',
    designation_fr: 'Hamacs Simples',
    slug: 'hamacs-simples',
    category: 'Hammocks et Tissus Aériens',
    order: 1,
    active: true,
  },
  {
    designation: 'Aerial Silks',
    designation_fr: 'Tissus Aériens',
    slug: 'tissus-aeriens',
    category: 'Hammocks et Tissus Aériens',
    order: 2,
    active: true,
  },
  {
    designation: 'Cocoon Hammocks',
    designation_fr: 'Hamacs Cocon',
    slug: 'hamacs-cocon',
    category: 'Hammocks et Tissus Aériens',
    order: 3,
    active: true,
  },
  {
    designation: 'Aerial Hoops',
    designation_fr: 'Cerceaux Aériens (Lyra)',
    slug: 'cerceaux-aeriens',
    category: 'Hammocks et Tissus Aériens',
    order: 4,
    active: true,
  },

  // === Équipements de Suspension ===
  {
    designation: 'TRX Alternatives',
    designation_fr: 'Alternatives TRX',
    slug: 'alternatives-trx',
    category: 'Équipements de Suspension',
    order: 1,
    active: true,
  },
  {
    designation: 'Suspension Straps',
    designation_fr: 'Sangles de Suspension',
    slug: 'sangles-suspension',
    category: 'Équipements de Suspension',
    order: 2,
    active: true,
  },
  {
    designation: 'Anchor Systems',
    designation_fr: 'Systèmes d\'Ancrage',
    slug: 'systemes-ancrage',
    category: 'Équipements de Suspension',
    order: 3,
    active: true,
  },

  // === Vêtements de Fitness ===
  {
    designation: 'Leggings',
    designation_fr: 'Leggings',
    slug: 'leggings',
    category: 'Vêtements de Fitness',
    order: 1,
    active: true,
  },
  {
    designation: 'Tops & Sports Bras',
    designation_fr: 'Tops et Brassières de Sport',
    slug: 'tops-brassières',
    category: 'Vêtements de Fitness',
    order: 2,
    active: true,
  },
  {
    designation: 'Full Outfits',
    designation_fr: 'Tenues Complètes',
    slug: 'tenues-completes',
    category: 'Vêtements de Fitness',
    order: 3,
    active: true,
  },

  // === Accessoires de Yoga ===
  {
    designation: 'Yoga Blocks',
    designation_fr: 'Blocs de Yoga',
    slug: 'blocs-yoga',
    category: 'Accessoires de Yoga',
    order: 1,
    active: true,
  },
  {
    designation: 'Yoga Straps',
    designation_fr: 'Sangles de Yoga',
    slug: 'sangles-yoga',
    category: 'Accessoires de Yoga',
    order: 2,
    active: true,
  },
  {
    designation: 'Foam Rollers',
    designation_fr: 'Rouleaux de Massage',
    slug: 'rouleaux-massage',
    category: 'Accessoires de Yoga',
    order: 3,
    active: true,
  },

  // === Kits d'Entraînement ===
  {
    designation: 'Beginner Kits',
    designation_fr: 'Kits Débutants',
    slug: 'kits-debutants',
    category: 'Kits d\'Entraînement',
    order: 1,
    active: true,
  },
  {
    designation: 'Advanced Kits',
    designation_fr: 'Kits Avancés',
    slug: 'kits-avances',
    category: 'Kits d\'Entraînement',
    order: 2,
    active: true,
  },

  // === Mats et Tapis ===
  {
    designation: 'Yoga Mats',
    designation_fr: 'Tapis de Yoga',
    slug: 'tapis-yoga',
    category: 'Mats et Tapis',
    order: 1,
    active: true,
  },
  {
    designation: 'Fitness Mats',
    designation_fr: 'Tapis de Fitness',
    slug: 'tapis-fitness',
    category: 'Mats et Tapis',
    order: 2,
    active: true,
  },

  // === Rigs et Structures ===
  {
    designation: 'Freestanding Rigs',
    designation_fr: 'Portiques Autoportants',
    slug: 'portiques-autoportants',
    category: 'Rigs et Structures',
    order: 1,
    active: true,
  },
  {
    designation: 'Ceiling Mounts',
    designation_fr: 'Fixations Plafond',
    slug: 'fixations-plafond',
    category: 'Rigs et Structures',
    order: 2,
    active: true,
  },
  {
    designation: 'Portable Rigs',
    designation_fr: 'Rigs Portables',
    slug: 'rigs-portables',
    category: 'Rigs et Structures',
    order: 3,
    active: true,
  },

  // === Compléments de Bien-Être ===
  {
    designation: 'Recovery Supplements',
    designation_fr: 'Compléments de Récupération',
    slug: 'complements-recuperation',
    category: 'Compléments de Bien-Être',
    order: 1,
    active: true,
  },
  {
    designation: 'Essential Oils',
    designation_fr: 'Huiles Essentielles',
    slug: 'huiles-essentielles',
    category: 'Compléments de Bien-Être',
    order: 2,
    active: true,
  },
];
